In [20]:
import numpy as np

In [21]:
arr = np.arange(0, 20)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
arr[6]

np.int64(6)

In [24]:
arr[-1]

np.int64(19)

In [25]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [26]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
arr[:4] = 15
arr

array([15, 15, 15, 15,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
slice_arr = arr[:7]

In [30]:
slice_arr

array([15, 15, 15, 15,  4,  5,  6])

In [31]:
slice_arr[:] = 67
slice_arr

array([67, 67, 67, 67, 67, 67, 67])

In [32]:
arr

array([67, 67, 67, 67, 67, 67, 67,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

на numpy срез не создоет копию, а ссылается на тот участок памяти в массиве. Такой объект называется view

In [33]:
slice_arr2 = arr[:3].copy()

In [34]:
arr_2d = np.random.randint(10, 99, (5,5))

In [35]:
arr_2d

array([[77, 20, 42, 95, 12],
       [39, 63, 21, 30, 26],
       [47, 32, 47, 10, 34],
       [49, 61, 22, 71, 48],
       [42, 13, 56, 65, 56]], dtype=int32)

In [36]:
arr_2d[2]

array([47, 32, 47, 10, 34], dtype=int32)

In [38]:
arr_2d[3, 4]

np.int32(48)

In [39]:
arr_2d[:2]

array([[77, 20, 42, 95, 12],
       [39, 63, 21, 30, 26]], dtype=int32)

In [40]:
arr_2d

array([[77, 20, 42, 95, 12],
       [39, 63, 21, 30, 26],
       [47, 32, 47, 10, 34],
       [49, 61, 22, 71, 48],
       [42, 13, 56, 65, 56]], dtype=int32)

In [41]:
arr_2d[:2, 1:]

array([[20, 42, 95, 12],
       [63, 21, 30, 26]], dtype=int32)

In [48]:
arr = np.random.randint(10, 99, 10)
arr

array([26, 17, 92, 39, 41, 43, 20, 86, 55, 89], dtype=int32)

In [49]:
arr > 50

array([False, False,  True, False, False, False, False,  True,  True,
        True])

In [50]:
bool_arr = arr > 50
bool_arr

array([False, False,  True, False, False, False, False,  True,  True,
        True])

In [54]:
arr[bool_arr]

array([92, 86, 55, 89], dtype=int32)

In [55]:
arr[bool_arr] = 0
arr

array([26, 17,  0, 39, 41, 43, 20,  0,  0,  0], dtype=int32)