In [40]:
import torch

### Тензор
- Скаляр - одно число - 0 мерный тензор
- Вектор - список чисел - 1 мерный тензор
- Матрица - 2 мерный тензор
- Изображение(RGB) - 3 мерный тензор
- Пачка изображений - 4 мерный тензор

In [41]:
scalar = torch.tensor(6)
print(f"Scalar: {scalar}, Shape: {scalar.shape}")

vector = torch.tensor([5, 9, 7])
print(f"Vector: {vector}, Shape: {vector.shape}")

matrix = torch.tensor([[25, 65],[12, 32],[33,33]])
print(f"Matrix: {matrix}, Shape: {matrix.shape}")

tensor3d = torch.randn((5, 5, 5))
print(f"Shape: {tensor3d.shape}")


Scalar: 6, Shape: torch.Size([])
Vector: tensor([5, 9, 7]), Shape: torch.Size([3])
Matrix: tensor([[25, 65],
        [12, 32],
        [33, 33]]), Shape: torch.Size([3, 2])
Shape: torch.Size([5, 5, 5])


In [42]:
# tensor generate
print(torch.zeros(5, 5))
print(torch.ones(5, 5))
print(torch.rand(5, 5))
print(torch.arange(0, 10, 2))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.7151, 0.9605, 0.2730, 0.5629, 0.2342],
        [0.1773, 0.9534, 0.7914, 0.5463, 0.6504],
        [0.9975, 0.7828, 0.9565, 0.8915, 0.1881],
        [0.0331, 0.3782, 0.0871, 0.3964, 0.3363],
        [0.8311, 0.8670, 0.2865, 0.3217, 0.2701]])
tensor([0, 2, 4, 6, 8])


In [43]:
a =torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a + b) # Сложение
print(a * b) # Покомпонентное умножение
print(torch.dot(a, b)) # Скалярное произведение

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor(32)


In [44]:
A = torch.tensor([[2, 3], [6, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print(A @ B)


tensor([[31., 36.],
        [58., 68.]])


In [45]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"
print(device)

cpu


In [46]:
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "no gpu")

None
False
no gpu
