In [1]:
import numpy as np

In [2]:
arr = np.arange(10, 20)

In [3]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
arr + 1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr - 25

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6])

In [6]:
arr + arr

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [7]:
arr * arr

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361])

In [8]:
arr2 = np.arange(10, 15)

In [9]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
5 / arr

array([0.5       , 0.45454545, 0.41666667, 0.38461538, 0.35714286,
       0.33333333, 0.3125    , 0.29411765, 0.27777778, 0.26315789])

In [11]:
np.sqrt(arr)

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [12]:
np.sin(arr)

array([-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [13]:
np.log(arr)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [14]:
arr.sum()

np.int64(145)

In [16]:
arr = np.random.randint(10, 99, 10)


In [17]:
arr

array([90, 35, 15, 62, 76, 89, 22, 71, 42, 57], dtype=int32)

In [24]:
arr.sum()

np.int64(559)

In [19]:
arr.mean()

np.float64(55.9)

In [25]:
arr.var()

np.float64(638.09)

In [26]:
arr.std()

np.float64(25.260443384865596)