In [1]:
import numpy as np

In [4]:
my_list = [5, 65, 35, 7]

list

In [3]:
type(my_list)

list

In [5]:
np.array(my_list)

array([ 5, 65, 35,  7])

In [6]:
my_array = np.array(my_list)

In [7]:
my_array

array([ 5, 65, 35,  7])

In [8]:
my_matrix = [[256, 48], [468, 34]]

In [9]:
my_matrix

[[256, 48], [468, 34]]

In [10]:
np_array = np.array(my_matrix)

In [11]:
np_array

array([[256,  48],
       [468,  34]])

In [12]:
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
array = np.arange(0, 15)

In [14]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
print(np_array)

[[256  48]
 [468  34]]


In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.arange(1, 255, 15)

array([  1,  16,  31,  46,  61,  76,  91, 106, 121, 136, 151, 166, 181,
       196, 211, 226, 241])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
two_dim = np.zeros((5, 5))

In [24]:
print(two_dim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [42]:
print(np.eye(5, k=1))

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [43]:
print(np.eye(5, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [48]:
print(np.eye(5, k=-1))

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [49]:
print(np.random.rand(5, 5))

[[0.47042881 0.69704691 0.85229293 0.90860465 0.45636563]
 [0.10500652 0.03057236 0.53888379 0.4393405  0.24140545]
 [0.89871651 0.61712943 0.27245681 0.38802591 0.74054203]
 [0.12976877 0.76238705 0.06864028 0.66568713 0.50547746]
 [0.45428806 0.42336094 0.84110778 0.2289553  0.68235525]]


In [51]:
print(np.random.randn(2, 2))

[[-0.64939284  1.46694419]
 [-0.16881575  1.9816244 ]]


In [52]:
print(np.random.randint(5, 150, 10))

[ 39  62  72  10  47  23  65 121  61  92]


In [59]:
print(np.random.randint(5, 150, (3, 3)))


[[ 79  92 121]
 [104 108 135]
 [ 57   6  92]]


In [55]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [56]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [57]:
arr = np.arange(20, 50)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [58]:
print(arr.reshape(5, 6))


[[20 21 22 23 24 25]
 [26 27 28 29 30 31]
 [32 33 34 35 36 37]
 [38 39 40 41 42 43]
 [44 45 46 47 48 49]]


In [64]:
rand_arr = np.random.randint(0, 120, 20)
print(rand_arr)


[ 29  37   1  63  59  20  32  75  57  21 107  88  48  90  58  41  91  59
  79  14]


In [65]:
rand_arr.argmax()

np.int64(10)

In [66]:
rand_arr.max()

np.int32(107)

In [67]:
rand_arr.min()

np.int32(1)

In [68]:
rand_arr.argmin()

np.int64(2)

In [69]:
rand_arr.dtype

dtype('int32')

In [70]:
arr.shape

(30,)

In [71]:
two_dim.shape

(5, 5)